/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';

/**
* The AlertsStatusInner model module.
* @module model/AlertsStatusInner
* @version 1.0.0
*/
export default class AlertsStatusInner {
    /**
    * Constructs a new <code>AlertsStatusInner</code>.
    * @alias module:model/AlertsStatusInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AlertsStatusInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlertsStatusInner} obj Optional instance to populate.
    * @return {module:model/AlertsStatusInner} The populated <code>AlertsStatusInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertsStatusInner();
                        
            
            if (data.hasOwnProperty('frame_id')) {
                obj['frame_id'] = ApiClient.convertToType(data['frame_id'], 'String');
            }
            if (data.hasOwnProperty('sensor')) {
                obj['sensor'] = ApiClient.convertToType(data['sensor'], Object);
            }
            if (data.hasOwnProperty('imei')) {
                obj['imei'] = ApiClient.convertToType(data['imei'], 'String');
            }
            if (data.hasOwnProperty('msg_time')) {
                obj['msg_time'] = ApiClient.convertToType(data['msg_time'], 'Number');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], BigDecimal);
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], BigDecimal);
            }
            if (data.hasOwnProperty('fuel_level')) {
                obj['fuel_level'] = ApiClient.convertToType(data['fuel_level'], BigDecimal);
            }
            if (data.hasOwnProperty('vehicle_id')) {
                obj['vehicle_id'] = ApiClient.convertToType(data['vehicle_id'], 'Number');
            }
            if (data.hasOwnProperty('driver_id')) {
                obj['driver_id'] = ApiClient.convertToType(data['driver_id'], 'Number');
            }
            if (data.hasOwnProperty('is_maintenance_enabled')) {
                obj['is_maintenance_enabled'] = ApiClient.convertToType(data['is_maintenance_enabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} frame_id
    */
    frame_id = undefined;
    /**
    * @member {Object} sensor
    */
    sensor = undefined;
    /**
    * @member {String} imei
    */
    imei = undefined;
    /**
    * @member {Number} msg_time
    */
    msg_time = undefined;
    /**
    * @member {module:model/BigDecimal} latitude
    */
    latitude = undefined;
    /**
    * @member {module:model/BigDecimal} longitude
    */
    longitude = undefined;
    /**
    * @member {module:model/BigDecimal} fuel_level
    */
    fuel_level = undefined;
    /**
    * @member {Number} vehicle_id
    */
    vehicle_id = undefined;
    /**
    * @member {Number} driver_id
    */
    driver_id = undefined;
    /**
    * @member {Boolean} is_maintenance_enabled
    */
    is_maintenance_enabled = undefined;




}
