/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AlertListDesc model module.
* @module model/AlertListDesc
* @version 1.0.0
*/
export default class AlertListDesc {
    /**
    * Constructs a new <code>AlertListDesc</code>.
    * @alias module:model/AlertListDesc
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AlertListDesc</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlertListDesc} obj Optional instance to populate.
    * @return {module:model/AlertListDesc} The populated <code>AlertListDesc</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertListDesc();
                        
            
        }
        return obj;
    }





}
