/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AlertsStatusInner from './AlertsStatusInner';

/**
* The AlertsStatus model module.
* @module model/AlertsStatus
* @version 1.0.0
*/
export default class AlertsStatus extends Array {
    /**
    * Constructs a new <code>AlertsStatus</code>.
    * @alias module:model/AlertsStatus
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>AlertsStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlertsStatus} obj Optional instance to populate.
    * @return {module:model/AlertsStatus} The populated <code>AlertsStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertsStatus();
            ApiClient.constructFromObject(data, obj, 'AlertsStatusInner');
            
            
        }
        return obj;
    }





}
