/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AlertListCode from './AlertListCode';
import AlertListDriver from './AlertListDriver';
import AlertListLevel from './AlertListLevel';
import AlertListVehicle from './AlertListVehicle';
import BigDecimal from './BigDecimal';

/**
* The AlertListList model module.
* @module model/AlertListList
* @version 1.0.0
*/
export default class AlertListList {
    /**
    * Constructs a new <code>AlertListList</code>.
    * @alias module:model/AlertListList
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AlertListList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlertListList} obj Optional instance to populate.
    * @return {module:model/AlertListList} The populated <code>AlertListList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertListList();
                        
            
            if (data.hasOwnProperty('fuel_level')) {
                obj['fuel_level'] = ApiClient.convertToType(data['fuel_level'], BigDecimal);
            }
            if (data.hasOwnProperty('smoothed_fuel_level')) {
                obj['smoothed_fuel_level'] = ApiClient.convertToType(data['smoothed_fuel_level'], BigDecimal);
            }
            if (data.hasOwnProperty('fuel_level_on_raise_start')) {
                obj['fuel_level_on_raise_start'] = ApiClient.convertToType(data['fuel_level_on_raise_start'], BigDecimal);
            }
            if (data.hasOwnProperty('action_status')) {
                obj['action_status'] = ApiClient.convertToType(data['action_status'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('nav_system_object_uid')) {
                obj['nav_system_object_uid'] = ApiClient.convertToType(data['nav_system_object_uid'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('is_closed')) {
                obj['is_closed'] = ApiClient.convertToType(data['is_closed'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('vehicle')) {
                obj['vehicle'] = AlertListVehicle.constructFromObject(data['vehicle']);
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = AlertListCode.constructFromObject(data['code']);
            }
            if (data.hasOwnProperty('driver')) {
                obj['driver'] = AlertListDriver.constructFromObject(data['driver']);
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = AlertListLevel.constructFromObject(data['level']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('is_maintenance_enabled')) {
                obj['is_maintenance_enabled'] = ApiClient.convertToType(data['is_maintenance_enabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/BigDecimal} fuel_level
    */
    fuel_level = undefined;
    /**
    * @member {module:model/BigDecimal} smoothed_fuel_level
    */
    smoothed_fuel_level = undefined;
    /**
    * @member {module:model/BigDecimal} fuel_level_on_raise_start
    */
    fuel_level_on_raise_start = undefined;
    /**
    * @member {Number} action_status
    */
    action_status = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} nav_system_object_uid
    */
    nav_system_object_uid = undefined;
    /**
    * @member {Number} created_at
    */
    created_at = undefined;
    /**
    * @member {Boolean} is_closed
    */
    is_closed = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {module:model/AlertListVehicle} vehicle
    */
    vehicle = undefined;
    /**
    * @member {module:model/AlertListCode} code
    */
    code = undefined;
    /**
    * @member {module:model/AlertListDriver} driver
    */
    driver = undefined;
    /**
    * @member {module:model/AlertListLevel} level
    */
    level = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {Boolean} is_maintenance_enabled
    */
    is_maintenance_enabled = undefined;




}
