/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AlertListCode model module.
* @module model/AlertListCode
* @version 0.0.1
*/
export default class AlertListCode {
    /**
    * Constructs a new <code>AlertListCode</code>.
    * @alias module:model/AlertListCode
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AlertListCode</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlertListCode} obj Optional instance to populate.
    * @return {module:model/AlertListCode} The populated <code>AlertListCode</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertListCode();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} code
    */
    code = undefined;
    /**
    * @member {String} description
    */
    description = undefined;




}
