/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AlertsStatusDesc model module.
* @module model/AlertsStatusDesc
* @version 1.0.0
*/
export default class AlertsStatusDesc {
    /**
    * Constructs a new <code>AlertsStatusDesc</code>.
    * @alias module:model/AlertsStatusDesc
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AlertsStatusDesc</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlertsStatusDesc} obj Optional instance to populate.
    * @return {module:model/AlertsStatusDesc} The populated <code>AlertsStatusDesc</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertsStatusDesc();
                        
            
        }
        return obj;
    }





}
