/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AuthorizedUser model module.
* @module model/AuthorizedUser
* @version 1.0.0
*/
export default class AuthorizedUser {
    /**
    * Constructs a new <code>AuthorizedUser</code>.
    * @alias module:model/AuthorizedUser
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AuthorizedUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthorizedUser} obj Optional instance to populate.
    * @return {module:model/AuthorizedUser} The populated <code>AuthorizedUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorizedUser();
                        
            
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('refresh_token')) {
                obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} token
    */
    token = undefined;
    /**
    * @member {String} refresh_token
    */
    refresh_token = undefined;




}
