/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CountryListInner model module.
* @module model/CountryListInner
* @version 1.0.0
*/
export default class CountryListInner {
    /**
    * Constructs a new <code>CountryListInner</code>.
    * @alias module:model/CountryListInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CountryListInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CountryListInner} obj Optional instance to populate.
    * @return {module:model/CountryListInner} The populated <code>CountryListInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountryListInner();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} code
    */
    code = undefined;




}
