/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateVehicleCategoryVehicleCategoryForm from './CreateVehicleCategoryVehicleCategoryForm';

/**
* The CreateVehicleCategory model module.
* @module model/CreateVehicleCategory
* @version 0.0.1
*/
export default class CreateVehicleCategory {
    /**
    * Constructs a new <code>CreateVehicleCategory</code>.
    * @alias module:model/CreateVehicleCategory
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CreateVehicleCategory</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateVehicleCategory} obj Optional instance to populate.
    * @return {module:model/CreateVehicleCategory} The populated <code>CreateVehicleCategory</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateVehicleCategory();
                        
            
            if (data.hasOwnProperty('vehicle_category_form')) {
                obj['vehicle_category_form'] = CreateVehicleCategoryVehicleCategoryForm.constructFromObject(data['vehicle_category_form']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/CreateVehicleCategoryVehicleCategoryForm} vehicle_category_form
    */
    vehicle_category_form = undefined;




}
