/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateProfileUserNavSystemAccessData model module.
* @module model/CreateProfileUserNavSystemAccessData
* @version 0.0.1
*/
export default class CreateProfileUserNavSystemAccessData {
    /**
    * Constructs a new <code>CreateProfileUserNavSystemAccessData</code>.
    * @alias module:model/CreateProfileUserNavSystemAccessData
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CreateProfileUserNavSystemAccessData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateProfileUserNavSystemAccessData} obj Optional instance to populate.
    * @return {module:model/CreateProfileUserNavSystemAccessData} The populated <code>CreateProfileUserNavSystemAccessData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProfileUserNavSystemAccessData();
                        
            
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('apikey')) {
                obj['apikey'] = ApiClient.convertToType(data['apikey'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} account
    */
    account = undefined;
    /**
    * @member {String} password
    */
    password = undefined;
    /**
    * @member {String} username
    */
    username = undefined;
    /**
    * @member {String} apikey
    */
    apikey = undefined;




}
