/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateVehicleCategoryVehicleCategoryForm model module.
* @module model/CreateVehicleCategoryVehicleCategoryForm
* @version 1.0.0
*/
export default class CreateVehicleCategoryVehicleCategoryForm {
    /**
    * Constructs a new <code>CreateVehicleCategoryVehicleCategoryForm</code>.
    * @alias module:model/CreateVehicleCategoryVehicleCategoryForm
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CreateVehicleCategoryVehicleCategoryForm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateVehicleCategoryVehicleCategoryForm} obj Optional instance to populate.
    * @return {module:model/CreateVehicleCategoryVehicleCategoryForm} The populated <code>CreateVehicleCategoryVehicleCategoryForm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateVehicleCategoryVehicleCategoryForm();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Number} owner
    */
    owner = undefined;
    /**
    * @member {Number} type
    */
    type = undefined;




}
