/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateProfileUser from './CreateProfileUser';

/**
* The CreateProfile model module.
* @module model/CreateProfile
* @version 1.0.0
*/
export default class CreateProfile {
    /**
    * Constructs a new <code>CreateProfile</code>.
    * @alias module:model/CreateProfile
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CreateProfile</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateProfile} obj Optional instance to populate.
    * @return {module:model/CreateProfile} The populated <code>CreateProfile</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProfile();
                        
            
            if (data.hasOwnProperty('user')) {
                obj['user'] = CreateProfileUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/CreateProfileUser} user
    */
    user = undefined;




}
