/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateProfileUserNavSystemAccessData from './CreateProfileUserNavSystemAccessData';

/**
* The CreateProfileUser model module.
* @module model/CreateProfileUser
* @version 1.0.0
*/
export default class CreateProfileUser {
    /**
    * Constructs a new <code>CreateProfileUser</code>.
    * @alias module:model/CreateProfileUser
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CreateProfileUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateProfileUser} obj Optional instance to populate.
    * @return {module:model/CreateProfileUser} The populated <code>CreateProfileUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProfileUser();
                        
            
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], ['Number']);
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('company_short_name')) {
                obj['company_short_name'] = ApiClient.convertToType(data['company_short_name'], 'String');
            }
            if (data.hasOwnProperty('notify_timezone')) {
                obj['notify_timezone'] = ApiClient.convertToType(data['notify_timezone'], 'Number');
            }
            if (data.hasOwnProperty('lang')) {
                obj['lang'] = ApiClient.convertToType(data['lang'], 'Number');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'Number');
            }
            if (data.hasOwnProperty('nav_system_access_data')) {
                obj['nav_system_access_data'] = CreateProfileUserNavSystemAccessData.constructFromObject(data['nav_system_access_data']);
            }
        }
        return obj;
    }

    /**
    * @member {String} firstname
    */
    firstname = undefined;
    /**
    * @member {String} lastname
    */
    lastname = undefined;
    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {String} phone
    */
    phone = undefined;
    /**
    * @member {String} comment
    */
    comment = undefined;
    /**
    * @member {Array.<Number>} groups
    */
    groups = undefined;
    /**
    * @member {String} company
    */
    company = undefined;
    /**
    * @member {String} company_short_name
    */
    company_short_name = undefined;
    /**
    * @member {Number} notify_timezone
    */
    notify_timezone = undefined;
    /**
    * @member {Number} lang
    */
    lang = undefined;
    /**
    * @member {Number} parent
    */
    parent = undefined;
    /**
    * @member {module:model/CreateProfileUserNavSystemAccessData} nav_system_access_data
    */
    nav_system_access_data = undefined;




}
