/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The FleetStatus model module.
* @module model/FleetStatus
* @version 1.0.0
*/
export default class FleetStatus {
    /**
    * Constructs a new <code>FleetStatus</code>.
    * @alias module:model/FleetStatus
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>FleetStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FleetStatus} obj Optional instance to populate.
    * @return {module:model/FleetStatus} The populated <code>FleetStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FleetStatus();
                        
            
            if (data.hasOwnProperty('realtime_stack')) {
                obj['realtime_stack'] = ApiClient.convertToType(data['realtime_stack'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} realtime_stack
    */
    realtime_stack = undefined;




}
