/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';

/**
* The FrameHistoryList model module.
* @module model/FrameHistoryList
* @version 0.0.1
*/
export default class FrameHistoryList {
    /**
    * Constructs a new <code>FrameHistoryList</code>.
    * @alias module:model/FrameHistoryList
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>FrameHistoryList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FrameHistoryList} obj Optional instance to populate.
    * @return {module:model/FrameHistoryList} The populated <code>FrameHistoryList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FrameHistoryList();
                        
            
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], BigDecimal);
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], BigDecimal);
            }
            if (data.hasOwnProperty('battery_level')) {
                obj['battery_level'] = ApiClient.convertToType(data['battery_level'], 'Number');
            }
            if (data.hasOwnProperty('engine_started')) {
                obj['engine_started'] = ApiClient.convertToType(data['engine_started'], 'Boolean');
            }
            if (data.hasOwnProperty('is_moving')) {
                obj['is_moving'] = ApiClient.convertToType(data['is_moving'], 'Boolean');
            }
            if (data.hasOwnProperty('fuel_level')) {
                obj['fuel_level'] = ApiClient.convertToType(data['fuel_level'], BigDecimal);
            }
            if (data.hasOwnProperty('msg_time')) {
                obj['msg_time'] = ApiClient.convertToType(data['msg_time'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/BigDecimal} latitude
    */
    latitude = undefined;
    /**
    * @member {module:model/BigDecimal} longitude
    */
    longitude = undefined;
    /**
    * @member {Number} battery_level
    */
    battery_level = undefined;
    /**
    * @member {Boolean} engine_started
    */
    engine_started = undefined;
    /**
    * @member {Boolean} is_moving
    */
    is_moving = undefined;
    /**
    * @member {module:model/BigDecimal} fuel_level
    */
    fuel_level = undefined;
    /**
    * @member {Number} msg_time
    */
    msg_time = undefined;




}
