/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The NotificationSettingsInner model module.
* @module model/NotificationSettingsInner
* @version 1.0.0
*/
export default class NotificationSettingsInner {
    /**
    * Constructs a new <code>NotificationSettingsInner</code>.
    * @alias module:model/NotificationSettingsInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NotificationSettingsInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NotificationSettingsInner} obj Optional instance to populate.
    * @return {module:model/NotificationSettingsInner} The populated <code>NotificationSettingsInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotificationSettingsInner();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('notify_by_email')) {
                obj['notify_by_email'] = ApiClient.convertToType(data['notify_by_email'], 'Boolean');
            }
            if (data.hasOwnProperty('notify_by_sms')) {
                obj['notify_by_sms'] = ApiClient.convertToType(data['notify_by_sms'], 'Boolean');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], Object);
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {Boolean} notify_by_email
    */
    notify_by_email = undefined;
    /**
    * @member {Boolean} notify_by_sms
    */
    notify_by_sms = undefined;
    /**
    * @member {Object} level
    */
    level = undefined;
    /**
    * @member {Object} code
    */
    code = undefined;




}
