/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RefuelsListInner from './RefuelsListInner';

/**
* The RefuelsList model module.
* @module model/RefuelsList
* @version 1.0.0
*/
export default class RefuelsList extends Array {
    /**
    * Constructs a new <code>RefuelsList</code>.
    * @alias module:model/RefuelsList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>RefuelsList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RefuelsList} obj Optional instance to populate.
    * @return {module:model/RefuelsList} The populated <code>RefuelsList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RefuelsList();
            ApiClient.constructFromObject(data, obj, 'RefuelsListInner');
            
            
        }
        return obj;
    }





}
