/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The StopppedConsumptionListList model module.
* @module model/StopppedConsumptionListList
* @version 0.0.1
*/
export default class StopppedConsumptionListList {
    /**
    * Constructs a new <code>StopppedConsumptionListList</code>.
    * @alias module:model/StopppedConsumptionListList
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>StopppedConsumptionListList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StopppedConsumptionListList} obj Optional instance to populate.
    * @return {module:model/StopppedConsumptionListList} The populated <code>StopppedConsumptionListList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StopppedConsumptionListList();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'String');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'String');
            }
            if (data.hasOwnProperty('finished_at')) {
                obj['finished_at'] = ApiClient.convertToType(data['finished_at'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} created_at
    */
    created_at = undefined;
    /**
    * @member {String} longitude
    */
    longitude = undefined;
    /**
    * @member {String} latitude
    */
    latitude = undefined;
    /**
    * @member {Number} finished_at
    */
    finished_at = undefined;




}
