/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateNotificationSettingsNotification from './UpdateNotificationSettingsNotification';

/**
* The UpdateNotificationSettings model module.
* @module model/UpdateNotificationSettings
* @version 1.0.0
*/
export default class UpdateNotificationSettings {
    /**
    * Constructs a new <code>UpdateNotificationSettings</code>.
    * @alias module:model/UpdateNotificationSettings
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateNotificationSettings</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateNotificationSettings} obj Optional instance to populate.
    * @return {module:model/UpdateNotificationSettings} The populated <code>UpdateNotificationSettings</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateNotificationSettings();
                        
            
            if (data.hasOwnProperty('notification')) {
                obj['notification'] = UpdateNotificationSettingsNotification.constructFromObject(data['notification']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UpdateNotificationSettingsNotification} notification
    */
    notification = undefined;




}
