/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';

/**
* The UpdateVehicleCategoryVehicleCategoryForm model module.
* @module model/UpdateVehicleCategoryVehicleCategoryForm
* @version 1.0.0
*/
export default class UpdateVehicleCategoryVehicleCategoryForm {
    /**
    * Constructs a new <code>UpdateVehicleCategoryVehicleCategoryForm</code>.
    * @alias module:model/UpdateVehicleCategoryVehicleCategoryForm
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateVehicleCategoryVehicleCategoryForm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateVehicleCategoryVehicleCategoryForm} obj Optional instance to populate.
    * @return {module:model/UpdateVehicleCategoryVehicleCategoryForm} The populated <code>UpdateVehicleCategoryVehicleCategoryForm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateVehicleCategoryVehicleCategoryForm();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('consumption')) {
                obj['consumption'] = ApiClient.convertToType(data['consumption'], BigDecimal);
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {module:model/BigDecimal} consumption
    */
    consumption = undefined;
    /**
    * @member {Number} owner
    */
    owner = undefined;




}
