/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateProfileUser from './UpdateProfileUser';

/**
* The UpdateProfile model module.
* @module model/UpdateProfile
* @version 0.0.1
*/
export default class UpdateProfile {
    /**
    * Constructs a new <code>UpdateProfile</code>.
    * @alias module:model/UpdateProfile
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateProfile</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateProfile} obj Optional instance to populate.
    * @return {module:model/UpdateProfile} The populated <code>UpdateProfile</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateProfile();
                        
            
            if (data.hasOwnProperty('user')) {
                obj['user'] = UpdateProfileUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UpdateProfileUser} user
    */
    user = undefined;




}
