/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UpdateVehicleVehicleTanks model module.
* @module model/UpdateVehicleVehicleTanks
* @version 0.0.1
*/
export default class UpdateVehicleVehicleTanks {
    /**
    * Constructs a new <code>UpdateVehicleVehicleTanks</code>.
    * @alias module:model/UpdateVehicleVehicleTanks
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateVehicleVehicleTanks</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateVehicleVehicleTanks} obj Optional instance to populate.
    * @return {module:model/UpdateVehicleVehicleTanks} The populated <code>UpdateVehicleVehicleTanks</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateVehicleVehicleTanks();
                        
            
            if (data.hasOwnProperty('tank_type')) {
                obj['tank_type'] = ApiClient.convertToType(data['tank_type'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} tank_type
    */
    tank_type = undefined;




}
