/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateNotificationSettingsNotificationAlert1 from './UpdateNotificationSettingsNotificationAlert1';
import UpdateNotificationSettingsNotificationAlert2 from './UpdateNotificationSettingsNotificationAlert2';
import UpdateNotificationSettingsNotificationAlert3 from './UpdateNotificationSettingsNotificationAlert3';
import UpdateNotificationSettingsNotificationAlert4 from './UpdateNotificationSettingsNotificationAlert4';
import UpdateNotificationSettingsNotificationAlert9 from './UpdateNotificationSettingsNotificationAlert9';

/**
* The UpdateNotificationSettingsNotification model module.
* @module model/UpdateNotificationSettingsNotification
* @version 0.0.1
*/
export default class UpdateNotificationSettingsNotification {
    /**
    * Constructs a new <code>UpdateNotificationSettingsNotification</code>.
    * @alias module:model/UpdateNotificationSettingsNotification
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateNotificationSettingsNotification</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateNotificationSettingsNotification} obj Optional instance to populate.
    * @return {module:model/UpdateNotificationSettingsNotification} The populated <code>UpdateNotificationSettingsNotification</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateNotificationSettingsNotification();
                        
            
            if (data.hasOwnProperty('alert_1')) {
                obj['alert_1'] = UpdateNotificationSettingsNotificationAlert1.constructFromObject(data['alert_1']);
            }
            if (data.hasOwnProperty('alert_2')) {
                obj['alert_2'] = UpdateNotificationSettingsNotificationAlert2.constructFromObject(data['alert_2']);
            }
            if (data.hasOwnProperty('alert_3')) {
                obj['alert_3'] = UpdateNotificationSettingsNotificationAlert3.constructFromObject(data['alert_3']);
            }
            if (data.hasOwnProperty('alert_4')) {
                obj['alert_4'] = UpdateNotificationSettingsNotificationAlert4.constructFromObject(data['alert_4']);
            }
            if (data.hasOwnProperty('alert_5')) {
                obj['alert_5'] = UpdateNotificationSettingsNotificationAlert4.constructFromObject(data['alert_5']);
            }
            if (data.hasOwnProperty('alert_6')) {
                obj['alert_6'] = UpdateNotificationSettingsNotificationAlert4.constructFromObject(data['alert_6']);
            }
            if (data.hasOwnProperty('alert_8')) {
                obj['alert_8'] = UpdateNotificationSettingsNotificationAlert4.constructFromObject(data['alert_8']);
            }
            if (data.hasOwnProperty('alert_9')) {
                obj['alert_9'] = UpdateNotificationSettingsNotificationAlert9.constructFromObject(data['alert_9']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UpdateNotificationSettingsNotificationAlert1} alert_1
    */
    alert_1 = undefined;
    /**
    * @member {module:model/UpdateNotificationSettingsNotificationAlert2} alert_2
    */
    alert_2 = undefined;
    /**
    * @member {module:model/UpdateNotificationSettingsNotificationAlert3} alert_3
    */
    alert_3 = undefined;
    /**
    * @member {module:model/UpdateNotificationSettingsNotificationAlert4} alert_4
    */
    alert_4 = undefined;
    /**
    * @member {module:model/UpdateNotificationSettingsNotificationAlert4} alert_5
    */
    alert_5 = undefined;
    /**
    * @member {module:model/UpdateNotificationSettingsNotificationAlert4} alert_6
    */
    alert_6 = undefined;
    /**
    * @member {module:model/UpdateNotificationSettingsNotificationAlert4} alert_8
    */
    alert_8 = undefined;
    /**
    * @member {module:model/UpdateNotificationSettingsNotificationAlert9} alert_9
    */
    alert_9 = undefined;




}
