/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UpdateNotificationSettingsNotificationAlert4 model module.
* @module model/UpdateNotificationSettingsNotificationAlert4
* @version 1.0.0
*/
export default class UpdateNotificationSettingsNotificationAlert4 {
    /**
    * Constructs a new <code>UpdateNotificationSettingsNotificationAlert4</code>.
    * @alias module:model/UpdateNotificationSettingsNotificationAlert4
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateNotificationSettingsNotificationAlert4</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateNotificationSettingsNotificationAlert4} obj Optional instance to populate.
    * @return {module:model/UpdateNotificationSettingsNotificationAlert4} The populated <code>UpdateNotificationSettingsNotificationAlert4</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateNotificationSettingsNotificationAlert4();
                        
            
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} level
    */
    level = undefined;




}
