/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UpdateNotificationSettingsNotificationAlert3 model module.
* @module model/UpdateNotificationSettingsNotificationAlert3
* @version 0.0.1
*/
export default class UpdateNotificationSettingsNotificationAlert3 {
    /**
    * Constructs a new <code>UpdateNotificationSettingsNotificationAlert3</code>.
    * @alias module:model/UpdateNotificationSettingsNotificationAlert3
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateNotificationSettingsNotificationAlert3</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateNotificationSettingsNotificationAlert3} obj Optional instance to populate.
    * @return {module:model/UpdateNotificationSettingsNotificationAlert3} The populated <code>UpdateNotificationSettingsNotificationAlert3</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateNotificationSettingsNotificationAlert3();
                        
            
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('notify_by_sms')) {
                obj['notify_by_sms'] = ApiClient.convertToType(data['notify_by_sms'], 'Number');
            }
            if (data.hasOwnProperty('notify_by_email')) {
                obj['notify_by_email'] = ApiClient.convertToType(data['notify_by_email'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} level
    */
    level = undefined;
    /**
    * @member {Number} notify_by_sms
    */
    notify_by_sms = undefined;
    /**
    * @member {Number} notify_by_email
    */
    notify_by_email = undefined;




}
