/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateVehicleCategoryVehicleCategoryForm from './UpdateVehicleCategoryVehicleCategoryForm';

/**
* The UpdateVehicleCategory model module.
* @module model/UpdateVehicleCategory
* @version 1.0.0
*/
export default class UpdateVehicleCategory {
    /**
    * Constructs a new <code>UpdateVehicleCategory</code>.
    * @alias module:model/UpdateVehicleCategory
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateVehicleCategory</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateVehicleCategory} obj Optional instance to populate.
    * @return {module:model/UpdateVehicleCategory} The populated <code>UpdateVehicleCategory</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateVehicleCategory();
                        
            
            if (data.hasOwnProperty('vehicle_category_form')) {
                obj['vehicle_category_form'] = UpdateVehicleCategoryVehicleCategoryForm.constructFromObject(data['vehicle_category_form']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UpdateVehicleCategoryVehicleCategoryForm} vehicle_category_form
    */
    vehicle_category_form = undefined;




}
