/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserProfileLang from './UserProfileLang';
import UserProfileListGeoLocalizationSettings from './UserProfileListGeoLocalizationSettings';
import UserProfileListGroups from './UserProfileListGroups';

/**
* The UserProfileListList model module.
* @module model/UserProfileListList
* @version 0.0.1
*/
export default class UserProfileListList {
    /**
    * Constructs a new <code>UserProfileListList</code>.
    * @alias module:model/UserProfileListList
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserProfileListList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserProfileListList} obj Optional instance to populate.
    * @return {module:model/UserProfileListList} The populated <code>UserProfileListList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserProfileListList();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [UserProfileListGroups]);
            }
            if (data.hasOwnProperty('locked')) {
                obj['locked'] = ApiClient.convertToType(data['locked'], 'Boolean');
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('lang')) {
                obj['lang'] = UserProfileLang.constructFromObject(data['lang']);
            }
            if (data.hasOwnProperty('geo_localization_settings')) {
                obj['geo_localization_settings'] = UserProfileListGeoLocalizationSettings.constructFromObject(data['geo_localization_settings']);
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {Array.<module:model/UserProfileListGroups>} groups
    */
    groups = undefined;
    /**
    * @member {Boolean} locked
    */
    locked = undefined;
    /**
    * @member {String} firstname
    */
    firstname = undefined;
    /**
    * @member {String} lastname
    */
    lastname = undefined;
    /**
    * @member {String} phone
    */
    phone = undefined;
    /**
    * @member {Number} parent_id
    */
    parent_id = undefined;
    /**
    * @member {String} company
    */
    company = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/UserProfileLang} lang
    */
    lang = undefined;
    /**
    * @member {module:model/UserProfileListGeoLocalizationSettings} geo_localization_settings
    */
    geo_localization_settings = undefined;




}
