/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UserCredentials model module.
* @module model/UserCredentials
* @version 0.0.1
*/
export default class UserCredentials {
    /**
    * Constructs a new <code>UserCredentials</code>.
    * @alias module:model/UserCredentials
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserCredentials</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserCredentials} obj Optional instance to populate.
    * @return {module:model/UserCredentials} The populated <code>UserCredentials</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCredentials();
                        
            
            if (data.hasOwnProperty('_username')) {
                obj['_username'] = ApiClient.convertToType(data['_username'], 'String');
            }
            if (data.hasOwnProperty('_password')) {
                obj['_password'] = ApiClient.convertToType(data['_password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} _username
    */
    _username = undefined;
    /**
    * @member {String} _password
    */
    _password = undefined;




}
