/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserProfileGeoLocalizationSettings from './UserProfileGeoLocalizationSettings';
import UserProfileGroups from './UserProfileGroups';
import UserProfileLang from './UserProfileLang';

/**
* The UserProfile model module.
* @module model/UserProfile
* @version 1.0.0
*/
export default class UserProfile {
    /**
    * Constructs a new <code>UserProfile</code>.
    * @alias module:model/UserProfile
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserProfile</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserProfile} obj Optional instance to populate.
    * @return {module:model/UserProfile} The populated <code>UserProfile</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserProfile();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [UserProfileGroups]);
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], ['String']);
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'String');
            }
            if (data.hasOwnProperty('association')) {
                obj['association'] = ApiClient.convertToType(data['association'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('company_short_name')) {
                obj['company_short_name'] = ApiClient.convertToType(data['company_short_name'], 'String');
            }
            if (data.hasOwnProperty('contract')) {
                obj['contract'] = ApiClient.convertToType(data['contract'], 'String');
            }
            if (data.hasOwnProperty('external_company')) {
                obj['external_company'] = ApiClient.convertToType(data['external_company'], 'String');
            }
            if (data.hasOwnProperty('nav_system_access_data')) {
                obj['nav_system_access_data'] = ApiClient.convertToType(data['nav_system_access_data'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('lang')) {
                obj['lang'] = UserProfileLang.constructFromObject(data['lang']);
            }
            if (data.hasOwnProperty('nav_system')) {
                obj['nav_system'] = ApiClient.convertToType(data['nav_system'], 'String');
            }
            if (data.hasOwnProperty('notify_by_email')) {
                obj['notify_by_email'] = ApiClient.convertToType(data['notify_by_email'], 'Boolean');
            }
            if (data.hasOwnProperty('notify_by_sms')) {
                obj['notify_by_sms'] = ApiClient.convertToType(data['notify_by_sms'], 'Boolean');
            }
            if (data.hasOwnProperty('notify_timezone')) {
                obj['notify_timezone'] = ApiClient.convertToType(data['notify_timezone'], 'String');
            }
            if (data.hasOwnProperty('partner_type')) {
                obj['partner_type'] = ApiClient.convertToType(data['partner_type'], 'String');
            }
            if (data.hasOwnProperty('is_terms_accepted')) {
                obj['is_terms_accepted'] = ApiClient.convertToType(data['is_terms_accepted'], 'Boolean');
            }
            if (data.hasOwnProperty('geo_localization_settings')) {
                obj['geo_localization_settings'] = UserProfileGeoLocalizationSettings.constructFromObject(data['geo_localization_settings']);
            }
            if (data.hasOwnProperty('api_token')) {
                obj['api_token'] = ApiClient.convertToType(data['api_token'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {Array.<module:model/UserProfileGroups>} groups
    */
    groups = undefined;
    /**
    * @member {Array.<String>} roles
    */
    roles = undefined;
    /**
    * @member {String} firstname
    */
    firstname = undefined;
    /**
    * @member {String} lastname
    */
    lastname = undefined;
    /**
    * @member {String} phone
    */
    phone = undefined;
    /**
    * @member {String} parent_id
    */
    parent_id = undefined;
    /**
    * @member {String} association
    */
    association = undefined;
    /**
    * @member {String} comment
    */
    comment = undefined;
    /**
    * @member {String} company
    */
    company = undefined;
    /**
    * @member {String} company_short_name
    */
    company_short_name = undefined;
    /**
    * @member {String} contract
    */
    contract = undefined;
    /**
    * @member {String} external_company
    */
    external_company = undefined;
    /**
    * @member {String} nav_system_access_data
    */
    nav_system_access_data = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/UserProfileLang} lang
    */
    lang = undefined;
    /**
    * @member {String} nav_system
    */
    nav_system = undefined;
    /**
    * @member {Boolean} notify_by_email
    */
    notify_by_email = undefined;
    /**
    * @member {Boolean} notify_by_sms
    */
    notify_by_sms = undefined;
    /**
    * @member {String} notify_timezone
    */
    notify_timezone = undefined;
    /**
    * @member {String} partner_type
    */
    partner_type = undefined;
    /**
    * @member {Boolean} is_terms_accepted
    */
    is_terms_accepted = undefined;
    /**
    * @member {module:model/UserProfileGeoLocalizationSettings} geo_localization_settings
    */
    geo_localization_settings = undefined;
    /**
    * @member {String} api_token
    */
    api_token = undefined;




}
