/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserGroupListInner from './UserGroupListInner';

/**
* The UserGroupList model module.
* @module model/UserGroupList
* @version 1.0.0
*/
export default class UserGroupList extends Array {
    /**
    * Constructs a new <code>UserGroupList</code>.
    * @alias module:model/UserGroupList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>UserGroupList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserGroupList} obj Optional instance to populate.
    * @return {module:model/UserGroupList} The populated <code>UserGroupList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserGroupList();
            ApiClient.constructFromObject(data, obj, 'UserGroupListInner');
            
            
        }
        return obj;
    }





}
