/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The VehicleCategoryOwner model module.
* @module model/VehicleCategoryOwner
* @version 1.0.0
*/
export default class VehicleCategoryOwner {
    /**
    * Constructs a new <code>VehicleCategoryOwner</code>.
    * @alias module:model/VehicleCategoryOwner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleCategoryOwner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleCategoryOwner} obj Optional instance to populate.
    * @return {module:model/VehicleCategoryOwner} The populated <code>VehicleCategoryOwner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleCategoryOwner();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('company_short_name')) {
                obj['company_short_name'] = ApiClient.convertToType(data['company_short_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {String} firstname
    */
    firstname = undefined;
    /**
    * @member {String} lastname
    */
    lastname = undefined;
    /**
    * @member {String} phone
    */
    phone = undefined;
    /**
    * @member {String} first_name
    */
    first_name = undefined;
    /**
    * @member {String} last_name
    */
    last_name = undefined;
    /**
    * @member {String} company
    */
    company = undefined;
    /**
    * @member {String} company_short_name
    */
    company_short_name = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;




}
