/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VehicleBrand from './VehicleBrand';
import VehicleModel from './VehicleModel';

/**
* The VehicleVersion model module.
* @module model/VehicleVersion
* @version 1.0.0
*/
export default class VehicleVersion {
    /**
    * Constructs a new <code>VehicleVersion</code>.
    * @alias module:model/VehicleVersion
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleVersion</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleVersion} obj Optional instance to populate.
    * @return {module:model/VehicleVersion} The populated <code>VehicleVersion</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleVersion();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('brand')) {
                obj['brand'] = VehicleBrand.constructFromObject(data['brand']);
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = VehicleModel.constructFromObject(data['model']);
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Number');
            }
            if (data.hasOwnProperty('ended_at')) {
                obj['ended_at'] = ApiClient.convertToType(data['ended_at'], 'String');
            }
            if (data.hasOwnProperty('tonnage')) {
                obj['tonnage'] = ApiClient.convertToType(data['tonnage'], 'Number');
            }
            if (data.hasOwnProperty('power')) {
                obj['power'] = ApiClient.convertToType(data['power'], 'Number');
            }
            if (data.hasOwnProperty('power_cv')) {
                obj['power_cv'] = ApiClient.convertToType(data['power_cv'], 'Number');
            }
            if (data.hasOwnProperty('axes')) {
                obj['axes'] = ApiClient.convertToType(data['axes'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {module:model/VehicleBrand} brand
    */
    brand = undefined;
    /**
    * @member {module:model/VehicleModel} model
    */
    model = undefined;
    /**
    * @member {Number} started_at
    */
    started_at = undefined;
    /**
    * @member {String} ended_at
    */
    ended_at = undefined;
    /**
    * @member {Number} tonnage
    */
    tonnage = undefined;
    /**
    * @member {Number} power
    */
    power = undefined;
    /**
    * @member {Number} power_cv
    */
    power_cv = undefined;
    /**
    * @member {String} axes
    */
    axes = undefined;




}
