/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VehicleFuelTypeListInner from './VehicleFuelTypeListInner';

/**
* The VehicleFuelTypeList model module.
* @module model/VehicleFuelTypeList
* @version 0.0.1
*/
export default class VehicleFuelTypeList extends Array {
    /**
    * Constructs a new <code>VehicleFuelTypeList</code>.
    * @alias module:model/VehicleFuelTypeList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>VehicleFuelTypeList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleFuelTypeList} obj Optional instance to populate.
    * @return {module:model/VehicleFuelTypeList} The populated <code>VehicleFuelTypeList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleFuelTypeList();
            ApiClient.constructFromObject(data, obj, 'VehicleFuelTypeListInner');
            
            
        }
        return obj;
    }





}
