/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The VehicleStatusTankTankType model module.
* @module model/VehicleStatusTankTankType
* @version 1.0.0
*/
export default class VehicleStatusTankTankType {
    /**
    * Constructs a new <code>VehicleStatusTankTankType</code>.
    * @alias module:model/VehicleStatusTankTankType
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleStatusTankTankType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleStatusTankTankType} obj Optional instance to populate.
    * @return {module:model/VehicleStatusTankTankType} The populated <code>VehicleStatusTankTankType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleStatusTankTankType();
                        
            
            if (data.hasOwnProperty('capacity')) {
                obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} capacity
    */
    capacity = undefined;




}
