/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VehicleTankType from './VehicleTankType';

/**
* The VehicleTanks model module.
* @module model/VehicleTanks
* @version 0.0.1
*/
export default class VehicleTanks {
    /**
    * Constructs a new <code>VehicleTanks</code>.
    * @alias module:model/VehicleTanks
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleTanks</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleTanks} obj Optional instance to populate.
    * @return {module:model/VehicleTanks} The populated <code>VehicleTanks</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleTanks();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('tank_type')) {
                obj['tank_type'] = VehicleTankType.constructFromObject(data['tank_type']);
            }
            if (data.hasOwnProperty('vehicle')) {
                obj['vehicle'] = ApiClient.convertToType(data['vehicle'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/VehicleTankType} tank_type
    */
    tank_type = undefined;
    /**
    * @member {String} vehicle
    */
    vehicle = undefined;




}
