/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The VehicleDailyStatsDesc model module.
* @module model/VehicleDailyStatsDesc
* @version 1.0.0
*/
export default class VehicleDailyStatsDesc {
    /**
    * Constructs a new <code>VehicleDailyStatsDesc</code>.
    * @alias module:model/VehicleDailyStatsDesc
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleDailyStatsDesc</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleDailyStatsDesc} obj Optional instance to populate.
    * @return {module:model/VehicleDailyStatsDesc} The populated <code>VehicleDailyStatsDesc</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleDailyStatsDesc();
                        
            
        }
        return obj;
    }





}
