/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VehicleStatusTankTankType from './VehicleStatusTankTankType';

/**
* The VehicleStatusTank model module.
* @module model/VehicleStatusTank
* @version 1.0.0
*/
export default class VehicleStatusTank {
    /**
    * Constructs a new <code>VehicleStatusTank</code>.
    * @alias module:model/VehicleStatusTank
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleStatusTank</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleStatusTank} obj Optional instance to populate.
    * @return {module:model/VehicleStatusTank} The populated <code>VehicleStatusTank</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleStatusTank();
                        
            
            if (data.hasOwnProperty('tank_type')) {
                obj['tank_type'] = VehicleStatusTankTankType.constructFromObject(data['tank_type']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VehicleStatusTankTankType} tank_type
    */
    tank_type = undefined;




}
