/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The VehicleStatusDesc model module.
* @module model/VehicleStatusDesc
* @version 0.0.1
*/
export default class VehicleStatusDesc {
    /**
    * Constructs a new <code>VehicleStatusDesc</code>.
    * @alias module:model/VehicleStatusDesc
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleStatusDesc</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleStatusDesc} obj Optional instance to populate.
    * @return {module:model/VehicleStatusDesc} The populated <code>VehicleStatusDesc</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleStatusDesc();
                        
            
        }
        return obj;
    }





}
