/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The VehicleListSensor model module.
* @module model/VehicleListSensor
* @version 1.0.0
*/
export default class VehicleListSensor {
    /**
    * Constructs a new <code>VehicleListSensor</code>.
    * @alias module:model/VehicleListSensor
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleListSensor</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleListSensor} obj Optional instance to populate.
    * @return {module:model/VehicleListSensor} The populated <code>VehicleListSensor</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleListSensor();
                        
            
            if (data.hasOwnProperty('gkeep_id')) {
                obj['gkeep_id'] = ApiClient.convertToType(data['gkeep_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} gkeep_id
    */
    gkeep_id = undefined;




}
