/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The VehicleListDesc model module.
* @module model/VehicleListDesc
* @version 0.0.1
*/
export default class VehicleListDesc {
    /**
    * Constructs a new <code>VehicleListDesc</code>.
    * @alias module:model/VehicleListDesc
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VehicleListDesc</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleListDesc} obj Optional instance to populate.
    * @return {module:model/VehicleListDesc} The populated <code>VehicleListDesc</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleListDesc();
                        
            
        }
        return obj;
    }





}
