/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import AuthorizedUser from '../model/AuthorizedUser';
import UserCredentials from '../model/UserCredentials';

/**
* UserAuthorization service.
* @module api/UserAuthorizationApi
* @version 0.0.1
*/
export default class UserAuthorizationApi {

    /**
    * Constructs a new UserAuthorizationApi. 
    * @alias module:api/UserAuthorizationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the authorize operation.
     * @callback module:api/UserAuthorizationApi~authorizeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AuthorizedUser} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * User authorization
     * @param {module:api/UserAuthorizationApi~authorizeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AuthorizedUser}
     */
    authorize(body, callback) {
      let postBody = body;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AuthorizedUser;

      return this.apiClient.callApi(
        '/api/login_check', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
