/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GkeepApi);
  }
}(this, function(expect, GkeepApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GkeepApi.AlertsStatusInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlertsStatusInner', function() {
    it('should create an instance of AlertsStatusInner', function() {
      // uncomment below and update the code to test AlertsStatusInner
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be.a(GkeepApi.AlertsStatusInner);
    });

    it('should have the property frameId (base name: "frame_id")', function() {
      // uncomment below and update the code to test the property frameId
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property sensor (base name: "sensor")', function() {
      // uncomment below and update the code to test the property sensor
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property imei (base name: "imei")', function() {
      // uncomment below and update the code to test the property imei
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property msgTime (base name: "msg_time")', function() {
      // uncomment below and update the code to test the property msgTime
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property fuelLevel (base name: "fuel_level")', function() {
      // uncomment below and update the code to test the property fuelLevel
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property vehicleId (base name: "vehicle_id")', function() {
      // uncomment below and update the code to test the property vehicleId
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property driverId (base name: "driver_id")', function() {
      // uncomment below and update the code to test the property driverId
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

    it('should have the property isMaintenanceEnabled (base name: "is_maintenance_enabled")', function() {
      // uncomment below and update the code to test the property isMaintenanceEnabled
      //var instane = new GkeepApi.AlertsStatusInner();
      //expect(instance).to.be();
    });

  });

}));
