/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GkeepApi);
  }
}(this, function(expect, GkeepApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GkeepApi.AlertList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlertList', function() {
    it('should create an instance of AlertList', function() {
      // uncomment below and update the code to test AlertList
      //var instane = new GkeepApi.AlertList();
      //expect(instance).to.be.a(GkeepApi.AlertList);
    });

    it('should have the property list (base name: "list")', function() {
      // uncomment below and update the code to test the property list
      //var instane = new GkeepApi.AlertList();
      //expect(instance).to.be();
    });

    it('should have the property count (base name: "count")', function() {
      // uncomment below and update the code to test the property count
      //var instane = new GkeepApi.AlertList();
      //expect(instance).to.be();
    });

    it('should have the property countPerPage (base name: "count_per_page")', function() {
      // uncomment below and update the code to test the property countPerPage
      //var instane = new GkeepApi.AlertList();
      //expect(instance).to.be();
    });

    it('should have the property pageCount (base name: "page_count")', function() {
      // uncomment below and update the code to test the property pageCount
      //var instane = new GkeepApi.AlertList();
      //expect(instance).to.be();
    });

    it('should have the property namePageParameter (base name: "name_page_parameter")', function() {
      // uncomment below and update the code to test the property namePageParameter
      //var instane = new GkeepApi.AlertList();
      //expect(instance).to.be();
    });

  });

}));
