/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GkeepApi);
  }
}(this, function(expect, GkeepApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GkeepApi.UpdateNotificationSettingsNotification();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateNotificationSettingsNotification', function() {
    it('should create an instance of UpdateNotificationSettingsNotification', function() {
      // uncomment below and update the code to test UpdateNotificationSettingsNotification
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be.a(GkeepApi.UpdateNotificationSettingsNotification);
    });

    it('should have the property alert1 (base name: "alert_1")', function() {
      // uncomment below and update the code to test the property alert1
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be();
    });

    it('should have the property alert2 (base name: "alert_2")', function() {
      // uncomment below and update the code to test the property alert2
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be();
    });

    it('should have the property alert3 (base name: "alert_3")', function() {
      // uncomment below and update the code to test the property alert3
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be();
    });

    it('should have the property alert4 (base name: "alert_4")', function() {
      // uncomment below and update the code to test the property alert4
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be();
    });

    it('should have the property alert5 (base name: "alert_5")', function() {
      // uncomment below and update the code to test the property alert5
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be();
    });

    it('should have the property alert6 (base name: "alert_6")', function() {
      // uncomment below and update the code to test the property alert6
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be();
    });

    it('should have the property alert8 (base name: "alert_8")', function() {
      // uncomment below and update the code to test the property alert8
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be();
    });

    it('should have the property alert9 (base name: "alert_9")', function() {
      // uncomment below and update the code to test the property alert9
      //var instane = new GkeepApi.UpdateNotificationSettingsNotification();
      //expect(instance).to.be();
    });

  });

}));
