/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GkeepApi);
  }
}(this, function(expect, GkeepApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GkeepApi.VehicleVersion();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VehicleVersion', function() {
    it('should create an instance of VehicleVersion', function() {
      // uncomment below and update the code to test VehicleVersion
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be.a(GkeepApi.VehicleVersion);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property brand (base name: "brand")', function() {
      // uncomment below and update the code to test the property brand
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property startedAt (base name: "started_at")', function() {
      // uncomment below and update the code to test the property startedAt
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property endedAt (base name: "ended_at")', function() {
      // uncomment below and update the code to test the property endedAt
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property tonnage (base name: "tonnage")', function() {
      // uncomment below and update the code to test the property tonnage
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property power (base name: "power")', function() {
      // uncomment below and update the code to test the property power
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property powerCv (base name: "power_cv")', function() {
      // uncomment below and update the code to test the property powerCv
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

    it('should have the property axes (base name: "axes")', function() {
      // uncomment below and update the code to test the property axes
      //var instane = new GkeepApi.VehicleVersion();
      //expect(instance).to.be();
    });

  });

}));
