/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GkeepApi);
  }
}(this, function(expect, GkeepApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GkeepApi.VehicleListList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VehicleListList', function() {
    it('should create an instance of VehicleListList', function() {
      // uncomment below and update the code to test VehicleListList
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be.a(GkeepApi.VehicleListList);
    });

    it('should have the property gkeepId (base name: "gkeep_id")', function() {
      // uncomment below and update the code to test the property gkeepId
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property driver (base name: "driver")', function() {
      // uncomment below and update the code to test the property driver
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property groups (base name: "groups")', function() {
      // uncomment below and update the code to test the property groups
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property photo (base name: "photo")', function() {
      // uncomment below and update the code to test the property photo
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property sensor (base name: "sensor")', function() {
      // uncomment below and update the code to test the property sensor
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property lastAlertAt (base name: "last_alert_at")', function() {
      // uncomment below and update the code to test the property lastAlertAt
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property firstFrameAt (base name: "first_frame_at")', function() {
      // uncomment below and update the code to test the property firstFrameAt
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

    it('should have the property isMaintenanceEnabled (base name: "is_maintenance_enabled")', function() {
      // uncomment below and update the code to test the property isMaintenanceEnabled
      //var instane = new GkeepApi.VehicleListList();
      //expect(instance).to.be();
    });

  });

}));
