/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GkeepApi);
  }
}(this, function(expect, GkeepApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GkeepApi.VehicleDailyStats();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VehicleDailyStats', function() {
    it('should create an instance of VehicleDailyStats', function() {
      // uncomment below and update the code to test VehicleDailyStats
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be.a(GkeepApi.VehicleDailyStats);
    });

    it('should have the property engineOnTime (base name: "engine_on_time")', function() {
      // uncomment below and update the code to test the property engineOnTime
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property stoppedTime (base name: "stopped_time")', function() {
      // uncomment below and update the code to test the property stoppedTime
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property fuelCost (base name: "fuel_cost")', function() {
      // uncomment below and update the code to test the property fuelCost
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property consumption (base name: "consumption")', function() {
      // uncomment below and update the code to test the property consumption
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property averageConsumption (base name: "average_consumption")', function() {
      // uncomment below and update the code to test the property averageConsumption
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property averageConsumptionHour (base name: "average_consumption_hour")', function() {
      // uncomment below and update the code to test the property averageConsumptionHour
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property abnormalConsumption (base name: "abnormal_consumption")', function() {
      // uncomment below and update the code to test the property abnormalConsumption
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property realConsumption (base name: "real_consumption")', function() {
      // uncomment below and update the code to test the property realConsumption
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

    it('should have the property objective (base name: "objective")', function() {
      // uncomment below and update the code to test the property objective
      //var instane = new GkeepApi.VehicleDailyStats();
      //expect(instance).to.be();
    });

  });

}));
