/**
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import AlertList from './model/AlertList';
import AlertListCode from './model/AlertListCode';
import AlertListDesc from './model/AlertListDesc';
import AlertListDriver from './model/AlertListDriver';
import AlertListLevel from './model/AlertListLevel';
import AlertListList from './model/AlertListList';
import AlertListVehicle from './model/AlertListVehicle';
import AlertListVehicleOwner from './model/AlertListVehicleOwner';
import AlertsStatus from './model/AlertsStatus';
import AlertsStatusDesc from './model/AlertsStatusDesc';
import AlertsStatusInner from './model/AlertsStatusInner';
import AuthorizedUser from './model/AuthorizedUser';
import CountryList from './model/CountryList';
import CountryListInner from './model/CountryListInner';
import CreateProfile from './model/CreateProfile';
import CreateProfileUser from './model/CreateProfileUser';
import CreateProfileUserNavSystemAccessData from './model/CreateProfileUserNavSystemAccessData';
import CreateVehicleCategory from './model/CreateVehicleCategory';
import CreateVehicleCategoryVehicleCategoryForm from './model/CreateVehicleCategoryVehicleCategoryForm';
import FleetStatus from './model/FleetStatus';
import FleetStatusDesc from './model/FleetStatusDesc';
import FrameHistory from './model/FrameHistory';
import FrameHistoryList from './model/FrameHistoryList';
import NotificationSettings from './model/NotificationSettings';
import NotificationSettingsInner from './model/NotificationSettingsInner';
import RefuelsList from './model/RefuelsList';
import RefuelsListInner from './model/RefuelsListInner';
import StopppedConsumptionList from './model/StopppedConsumptionList';
import StopppedConsumptionListList from './model/StopppedConsumptionListList';
import TankTypeList from './model/TankTypeList';
import TankTypeListInner from './model/TankTypeListInner';
import UpdateNotificationSettings from './model/UpdateNotificationSettings';
import UpdateNotificationSettingsNotification from './model/UpdateNotificationSettingsNotification';
import UpdateNotificationSettingsNotificationAlert1 from './model/UpdateNotificationSettingsNotificationAlert1';
import UpdateNotificationSettingsNotificationAlert2 from './model/UpdateNotificationSettingsNotificationAlert2';
import UpdateNotificationSettingsNotificationAlert3 from './model/UpdateNotificationSettingsNotificationAlert3';
import UpdateNotificationSettingsNotificationAlert4 from './model/UpdateNotificationSettingsNotificationAlert4';
import UpdateNotificationSettingsNotificationAlert9 from './model/UpdateNotificationSettingsNotificationAlert9';
import UpdateProfile from './model/UpdateProfile';
import UpdateProfileUser from './model/UpdateProfileUser';
import UpdateVehicle from './model/UpdateVehicle';
import UpdateVehicleCategory from './model/UpdateVehicleCategory';
import UpdateVehicleCategoryVehicleCategoryForm from './model/UpdateVehicleCategoryVehicleCategoryForm';
import UpdateVehicleVehicle from './model/UpdateVehicleVehicle';
import UpdateVehicleVehicleTanks from './model/UpdateVehicleVehicleTanks';
import UserCredentials from './model/UserCredentials';
import UserLevel from './model/UserLevel';
import UserProfile from './model/UserProfile';
import UserProfileGeoLocalizationSettings from './model/UserProfileGeoLocalizationSettings';
import UserProfileGroups from './model/UserProfileGroups';
import UserProfileLang from './model/UserProfileLang';
import UserProfileList from './model/UserProfileList';
import UserProfileListGeoLocalizationSettings from './model/UserProfileListGeoLocalizationSettings';
import UserProfileListGroups from './model/UserProfileListGroups';
import UserProfileListList from './model/UserProfileListList';
import Vehicle from './model/Vehicle';
import VehicleBrand from './model/VehicleBrand';
import VehicleBrandList from './model/VehicleBrandList';
import VehicleBrandListInner from './model/VehicleBrandListInner';
import VehicleCategory from './model/VehicleCategory';
import VehicleCategoryList from './model/VehicleCategoryList';
import VehicleCategoryListList from './model/VehicleCategoryListList';
import VehicleCategoryOwner from './model/VehicleCategoryOwner';
import VehicleCategoryType from './model/VehicleCategoryType';
import VehicleCountry from './model/VehicleCountry';
import VehicleDailyStats from './model/VehicleDailyStats';
import VehicleDailyStatsDesc from './model/VehicleDailyStatsDesc';
import VehicleDriver from './model/VehicleDriver';
import VehicleFuelTypeList from './model/VehicleFuelTypeList';
import VehicleFuelTypeListInner from './model/VehicleFuelTypeListInner';
import VehicleList from './model/VehicleList';
import VehicleListDesc from './model/VehicleListDesc';
import VehicleListGroups from './model/VehicleListGroups';
import VehicleListList from './model/VehicleListList';
import VehicleListSensor from './model/VehicleListSensor';
import VehicleMaintenance from './model/VehicleMaintenance';
import VehicleModel from './model/VehicleModel';
import VehicleModelList from './model/VehicleModelList';
import VehicleModelListList from './model/VehicleModelListList';
import VehicleNationalTypeList from './model/VehicleNationalTypeList';
import VehicleNationalTypeListInner from './model/VehicleNationalTypeListInner';
import VehicleNavSystem from './model/VehicleNavSystem';
import VehicleOwner from './model/VehicleOwner';
import VehiclePropertyList from './model/VehiclePropertyList';
import VehiclePropertyListInner from './model/VehiclePropertyListInner';
import VehicleSensor from './model/VehicleSensor';
import VehicleStatus from './model/VehicleStatus';
import VehicleStatusDesc from './model/VehicleStatusDesc';
import VehicleStatusTank from './model/VehicleStatusTank';
import VehicleStatusTankTankType from './model/VehicleStatusTankTankType';
import VehicleStatusTanks from './model/VehicleStatusTanks';
import VehicleStatusVehicle from './model/VehicleStatusVehicle';
import VehicleStatusVehicleDriver from './model/VehicleStatusVehicleDriver';
import VehicleTankPosition from './model/VehicleTankPosition';
import VehicleTankType from './model/VehicleTankType';
import VehicleTanks from './model/VehicleTanks';
import VehicleTechnical from './model/VehicleTechnical';
import VehicleTypeList from './model/VehicleTypeList';
import VehicleVersion from './model/VehicleVersion';
import VehicleVersionList from './model/VehicleVersionList';
import VehicleVersionListList from './model/VehicleVersionListList';
import UserAuthorizationApi from './api/UserAuthorizationApi';
import V1Api from './api/V1Api';
import V2Api from './api/V2Api';

/**
* Gkeep_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GkeepApi = require('index'); // See note below*.
* var xxxSvc = new GkeepApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GkeepApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GkeepApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GkeepApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AlertList model constructor.
     * @property {module:model/AlertList}
     */
    AlertList,

    /**
     * The AlertListCode model constructor.
     * @property {module:model/AlertListCode}
     */
    AlertListCode,

    /**
     * The AlertListDesc model constructor.
     * @property {module:model/AlertListDesc}
     */
    AlertListDesc,

    /**
     * The AlertListDriver model constructor.
     * @property {module:model/AlertListDriver}
     */
    AlertListDriver,

    /**
     * The AlertListLevel model constructor.
     * @property {module:model/AlertListLevel}
     */
    AlertListLevel,

    /**
     * The AlertListList model constructor.
     * @property {module:model/AlertListList}
     */
    AlertListList,

    /**
     * The AlertListVehicle model constructor.
     * @property {module:model/AlertListVehicle}
     */
    AlertListVehicle,

    /**
     * The AlertListVehicleOwner model constructor.
     * @property {module:model/AlertListVehicleOwner}
     */
    AlertListVehicleOwner,

    /**
     * The AlertsStatus model constructor.
     * @property {module:model/AlertsStatus}
     */
    AlertsStatus,

    /**
     * The AlertsStatusDesc model constructor.
     * @property {module:model/AlertsStatusDesc}
     */
    AlertsStatusDesc,

    /**
     * The AlertsStatusInner model constructor.
     * @property {module:model/AlertsStatusInner}
     */
    AlertsStatusInner,

    /**
     * The AuthorizedUser model constructor.
     * @property {module:model/AuthorizedUser}
     */
    AuthorizedUser,

    /**
     * The CountryList model constructor.
     * @property {module:model/CountryList}
     */
    CountryList,

    /**
     * The CountryListInner model constructor.
     * @property {module:model/CountryListInner}
     */
    CountryListInner,

    /**
     * The CreateProfile model constructor.
     * @property {module:model/CreateProfile}
     */
    CreateProfile,

    /**
     * The CreateProfileUser model constructor.
     * @property {module:model/CreateProfileUser}
     */
    CreateProfileUser,

    /**
     * The CreateProfileUserNavSystemAccessData model constructor.
     * @property {module:model/CreateProfileUserNavSystemAccessData}
     */
    CreateProfileUserNavSystemAccessData,

    /**
     * The CreateVehicleCategory model constructor.
     * @property {module:model/CreateVehicleCategory}
     */
    CreateVehicleCategory,

    /**
     * The CreateVehicleCategoryVehicleCategoryForm model constructor.
     * @property {module:model/CreateVehicleCategoryVehicleCategoryForm}
     */
    CreateVehicleCategoryVehicleCategoryForm,

    /**
     * The FleetStatus model constructor.
     * @property {module:model/FleetStatus}
     */
    FleetStatus,

    /**
     * The FleetStatusDesc model constructor.
     * @property {module:model/FleetStatusDesc}
     */
    FleetStatusDesc,

    /**
     * The FrameHistory model constructor.
     * @property {module:model/FrameHistory}
     */
    FrameHistory,

    /**
     * The FrameHistoryList model constructor.
     * @property {module:model/FrameHistoryList}
     */
    FrameHistoryList,

    /**
     * The NotificationSettings model constructor.
     * @property {module:model/NotificationSettings}
     */
    NotificationSettings,

    /**
     * The NotificationSettingsInner model constructor.
     * @property {module:model/NotificationSettingsInner}
     */
    NotificationSettingsInner,

    /**
     * The RefuelsList model constructor.
     * @property {module:model/RefuelsList}
     */
    RefuelsList,

    /**
     * The RefuelsListInner model constructor.
     * @property {module:model/RefuelsListInner}
     */
    RefuelsListInner,

    /**
     * The StopppedConsumptionList model constructor.
     * @property {module:model/StopppedConsumptionList}
     */
    StopppedConsumptionList,

    /**
     * The StopppedConsumptionListList model constructor.
     * @property {module:model/StopppedConsumptionListList}
     */
    StopppedConsumptionListList,

    /**
     * The TankTypeList model constructor.
     * @property {module:model/TankTypeList}
     */
    TankTypeList,

    /**
     * The TankTypeListInner model constructor.
     * @property {module:model/TankTypeListInner}
     */
    TankTypeListInner,

    /**
     * The UpdateNotificationSettings model constructor.
     * @property {module:model/UpdateNotificationSettings}
     */
    UpdateNotificationSettings,

    /**
     * The UpdateNotificationSettingsNotification model constructor.
     * @property {module:model/UpdateNotificationSettingsNotification}
     */
    UpdateNotificationSettingsNotification,

    /**
     * The UpdateNotificationSettingsNotificationAlert1 model constructor.
     * @property {module:model/UpdateNotificationSettingsNotificationAlert1}
     */
    UpdateNotificationSettingsNotificationAlert1,

    /**
     * The UpdateNotificationSettingsNotificationAlert2 model constructor.
     * @property {module:model/UpdateNotificationSettingsNotificationAlert2}
     */
    UpdateNotificationSettingsNotificationAlert2,

    /**
     * The UpdateNotificationSettingsNotificationAlert3 model constructor.
     * @property {module:model/UpdateNotificationSettingsNotificationAlert3}
     */
    UpdateNotificationSettingsNotificationAlert3,

    /**
     * The UpdateNotificationSettingsNotificationAlert4 model constructor.
     * @property {module:model/UpdateNotificationSettingsNotificationAlert4}
     */
    UpdateNotificationSettingsNotificationAlert4,

    /**
     * The UpdateNotificationSettingsNotificationAlert9 model constructor.
     * @property {module:model/UpdateNotificationSettingsNotificationAlert9}
     */
    UpdateNotificationSettingsNotificationAlert9,

    /**
     * The UpdateProfile model constructor.
     * @property {module:model/UpdateProfile}
     */
    UpdateProfile,

    /**
     * The UpdateProfileUser model constructor.
     * @property {module:model/UpdateProfileUser}
     */
    UpdateProfileUser,

    /**
     * The UpdateVehicle model constructor.
     * @property {module:model/UpdateVehicle}
     */
    UpdateVehicle,

    /**
     * The UpdateVehicleCategory model constructor.
     * @property {module:model/UpdateVehicleCategory}
     */
    UpdateVehicleCategory,

    /**
     * The UpdateVehicleCategoryVehicleCategoryForm model constructor.
     * @property {module:model/UpdateVehicleCategoryVehicleCategoryForm}
     */
    UpdateVehicleCategoryVehicleCategoryForm,

    /**
     * The UpdateVehicleVehicle model constructor.
     * @property {module:model/UpdateVehicleVehicle}
     */
    UpdateVehicleVehicle,

    /**
     * The UpdateVehicleVehicleTanks model constructor.
     * @property {module:model/UpdateVehicleVehicleTanks}
     */
    UpdateVehicleVehicleTanks,

    /**
     * The UserCredentials model constructor.
     * @property {module:model/UserCredentials}
     */
    UserCredentials,

    /**
     * The UserLevel model constructor.
     * @property {module:model/UserLevel}
     */
    UserLevel,

    /**
     * The UserProfile model constructor.
     * @property {module:model/UserProfile}
     */
    UserProfile,

    /**
     * The UserProfileGeoLocalizationSettings model constructor.
     * @property {module:model/UserProfileGeoLocalizationSettings}
     */
    UserProfileGeoLocalizationSettings,

    /**
     * The UserProfileGroups model constructor.
     * @property {module:model/UserProfileGroups}
     */
    UserProfileGroups,

    /**
     * The UserProfileLang model constructor.
     * @property {module:model/UserProfileLang}
     */
    UserProfileLang,

    /**
     * The UserProfileList model constructor.
     * @property {module:model/UserProfileList}
     */
    UserProfileList,

    /**
     * The UserProfileListGeoLocalizationSettings model constructor.
     * @property {module:model/UserProfileListGeoLocalizationSettings}
     */
    UserProfileListGeoLocalizationSettings,

    /**
     * The UserProfileListGroups model constructor.
     * @property {module:model/UserProfileListGroups}
     */
    UserProfileListGroups,

    /**
     * The UserProfileListList model constructor.
     * @property {module:model/UserProfileListList}
     */
    UserProfileListList,

    /**
     * The Vehicle model constructor.
     * @property {module:model/Vehicle}
     */
    Vehicle,

    /**
     * The VehicleBrand model constructor.
     * @property {module:model/VehicleBrand}
     */
    VehicleBrand,

    /**
     * The VehicleBrandList model constructor.
     * @property {module:model/VehicleBrandList}
     */
    VehicleBrandList,

    /**
     * The VehicleBrandListInner model constructor.
     * @property {module:model/VehicleBrandListInner}
     */
    VehicleBrandListInner,

    /**
     * The VehicleCategory model constructor.
     * @property {module:model/VehicleCategory}
     */
    VehicleCategory,

    /**
     * The VehicleCategoryList model constructor.
     * @property {module:model/VehicleCategoryList}
     */
    VehicleCategoryList,

    /**
     * The VehicleCategoryListList model constructor.
     * @property {module:model/VehicleCategoryListList}
     */
    VehicleCategoryListList,

    /**
     * The VehicleCategoryOwner model constructor.
     * @property {module:model/VehicleCategoryOwner}
     */
    VehicleCategoryOwner,

    /**
     * The VehicleCategoryType model constructor.
     * @property {module:model/VehicleCategoryType}
     */
    VehicleCategoryType,

    /**
     * The VehicleCountry model constructor.
     * @property {module:model/VehicleCountry}
     */
    VehicleCountry,

    /**
     * The VehicleDailyStats model constructor.
     * @property {module:model/VehicleDailyStats}
     */
    VehicleDailyStats,

    /**
     * The VehicleDailyStatsDesc model constructor.
     * @property {module:model/VehicleDailyStatsDesc}
     */
    VehicleDailyStatsDesc,

    /**
     * The VehicleDriver model constructor.
     * @property {module:model/VehicleDriver}
     */
    VehicleDriver,

    /**
     * The VehicleFuelTypeList model constructor.
     * @property {module:model/VehicleFuelTypeList}
     */
    VehicleFuelTypeList,

    /**
     * The VehicleFuelTypeListInner model constructor.
     * @property {module:model/VehicleFuelTypeListInner}
     */
    VehicleFuelTypeListInner,

    /**
     * The VehicleList model constructor.
     * @property {module:model/VehicleList}
     */
    VehicleList,

    /**
     * The VehicleListDesc model constructor.
     * @property {module:model/VehicleListDesc}
     */
    VehicleListDesc,

    /**
     * The VehicleListGroups model constructor.
     * @property {module:model/VehicleListGroups}
     */
    VehicleListGroups,

    /**
     * The VehicleListList model constructor.
     * @property {module:model/VehicleListList}
     */
    VehicleListList,

    /**
     * The VehicleListSensor model constructor.
     * @property {module:model/VehicleListSensor}
     */
    VehicleListSensor,

    /**
     * The VehicleMaintenance model constructor.
     * @property {module:model/VehicleMaintenance}
     */
    VehicleMaintenance,

    /**
     * The VehicleModel model constructor.
     * @property {module:model/VehicleModel}
     */
    VehicleModel,

    /**
     * The VehicleModelList model constructor.
     * @property {module:model/VehicleModelList}
     */
    VehicleModelList,

    /**
     * The VehicleModelListList model constructor.
     * @property {module:model/VehicleModelListList}
     */
    VehicleModelListList,

    /**
     * The VehicleNationalTypeList model constructor.
     * @property {module:model/VehicleNationalTypeList}
     */
    VehicleNationalTypeList,

    /**
     * The VehicleNationalTypeListInner model constructor.
     * @property {module:model/VehicleNationalTypeListInner}
     */
    VehicleNationalTypeListInner,

    /**
     * The VehicleNavSystem model constructor.
     * @property {module:model/VehicleNavSystem}
     */
    VehicleNavSystem,

    /**
     * The VehicleOwner model constructor.
     * @property {module:model/VehicleOwner}
     */
    VehicleOwner,

    /**
     * The VehiclePropertyList model constructor.
     * @property {module:model/VehiclePropertyList}
     */
    VehiclePropertyList,

    /**
     * The VehiclePropertyListInner model constructor.
     * @property {module:model/VehiclePropertyListInner}
     */
    VehiclePropertyListInner,

    /**
     * The VehicleSensor model constructor.
     * @property {module:model/VehicleSensor}
     */
    VehicleSensor,

    /**
     * The VehicleStatus model constructor.
     * @property {module:model/VehicleStatus}
     */
    VehicleStatus,

    /**
     * The VehicleStatusDesc model constructor.
     * @property {module:model/VehicleStatusDesc}
     */
    VehicleStatusDesc,

    /**
     * The VehicleStatusTank model constructor.
     * @property {module:model/VehicleStatusTank}
     */
    VehicleStatusTank,

    /**
     * The VehicleStatusTankTankType model constructor.
     * @property {module:model/VehicleStatusTankTankType}
     */
    VehicleStatusTankTankType,

    /**
     * The VehicleStatusTanks model constructor.
     * @property {module:model/VehicleStatusTanks}
     */
    VehicleStatusTanks,

    /**
     * The VehicleStatusVehicle model constructor.
     * @property {module:model/VehicleStatusVehicle}
     */
    VehicleStatusVehicle,

    /**
     * The VehicleStatusVehicleDriver model constructor.
     * @property {module:model/VehicleStatusVehicleDriver}
     */
    VehicleStatusVehicleDriver,

    /**
     * The VehicleTankPosition model constructor.
     * @property {module:model/VehicleTankPosition}
     */
    VehicleTankPosition,

    /**
     * The VehicleTankType model constructor.
     * @property {module:model/VehicleTankType}
     */
    VehicleTankType,

    /**
     * The VehicleTanks model constructor.
     * @property {module:model/VehicleTanks}
     */
    VehicleTanks,

    /**
     * The VehicleTechnical model constructor.
     * @property {module:model/VehicleTechnical}
     */
    VehicleTechnical,

    /**
     * The VehicleTypeList model constructor.
     * @property {module:model/VehicleTypeList}
     */
    VehicleTypeList,

    /**
     * The VehicleVersion model constructor.
     * @property {module:model/VehicleVersion}
     */
    VehicleVersion,

    /**
     * The VehicleVersionList model constructor.
     * @property {module:model/VehicleVersionList}
     */
    VehicleVersionList,

    /**
     * The VehicleVersionListList model constructor.
     * @property {module:model/VehicleVersionListList}
     */
    VehicleVersionListList,

    /**
    * The UserAuthorizationApi service constructor.
    * @property {module:api/UserAuthorizationApi}
    */
    UserAuthorizationApi,

    /**
    * The V1Api service constructor.
    * @property {module:api/V1Api}
    */
    V1Api,

    /**
    * The V2Api service constructor.
    * @property {module:api/V2Api}
    */
    V2Api
};
